<template>
  <div class="notification-page"><section class="page-intro"><div><span class="page-eyebrow">PLATFORM INBOX</span><h2>平台消息</h2><p>集中查看审核、异常监管和投诉仲裁待办。</p></div><div class="intro-count"><strong>{{ store.unreadCount }}</strong><span>条未读</span></div></section><section class="panel filter-panel"><el-segmented v-model="filter" :options="options" /><el-button v-if="store.unreadCount" type="primary" plain @click="readAll">全部已读</el-button></section><section class="notification-list"><article v-for="item in store.notifications" :key="item.notificationId" class="panel notification-item" :class="{ unread: !item.read }" @click="open(item)"><div class="notification-symbol" :class="item.category.toLowerCase()">{{ symbol(item.category) }}</div><div class="notification-copy"><div><strong>{{ item.title }}</strong><span v-if="!item.read" class="unread-dot" /></div><p>{{ item.content }}</p><small>{{ categoryText(item.category) }} · {{ item.createTime }}</small></div><el-icon><ArrowRight /></el-icon></article><el-empty v-if="!store.loading && !store.notifications.length" description="暂无平台消息" /></section></div>
</template>
<script setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useNotificationStore } from '../../stores/notification.js'
const router = useRouter(); const store = useNotificationStore(); const filter = ref('all'); const options = [{ label: '全部', value: 'all' }, { label: '未读', value: 'unread' }, { label: '审核', value: 'REVIEW' }, { label: '异常', value: 'EXCEPTION' }, { label: '投诉', value: 'COMPLAINT' }]; function load() { const params = filter.value === 'unread' ? { unreadOnly: true } : filter.value === 'all' ? {} : { category: filter.value }; return store.fetchNotifications(params) } function categoryText(value) { return ({ REVIEW: '审核待办', EXCEPTION: '异常监管', COMPLAINT: '投诉仲裁', SYSTEM: '系统消息' }[value] || value) } function symbol(value) { return ({ REVIEW: '审', EXCEPTION: '异', COMPLAINT: '诉', SYSTEM: '系' }[value] || '讯') } async function open(item) { if (!item.read) await store.markAsRead(item.notificationId); if (item.targetPath) router.push(item.targetPath) } async function readAll() { await store.markAllAsRead(); ElMessage.success('平台消息已全部标为已读') } watch(filter, load, { immediate: true })
</script>
<style scoped>
.notification-list{display:grid;gap:14px;margin-top:18px}.notification-item{display:flex;align-items:center;gap:16px;padding:19px 22px;cursor:pointer;transition:.2s}.notification-item:hover{transform:translateY(-2px);box-shadow:0 16px 38px rgba(32,51,97,.09)}.notification-item.unread{border-color:#b9c9f8;background:#fbfcff}.notification-symbol{display:grid;width:48px;height:48px;flex-shrink:0;place-items:center;border-radius:15px;color:#fff;font-weight:800;background:#66788c}.notification-symbol.review{background:#3156d3}.notification-symbol.exception{background:#e7833b}.notification-symbol.complaint{background:#e55b63}.notification-copy{min-width:0;flex:1}.notification-copy>div{display:flex;align-items:center;gap:9px}.notification-copy strong{font-size:14px}.notification-copy p{margin:7px 0;color:#68728a;font-size:12px;line-height:1.6}.notification-copy small{color:#98a2b5}.unread-dot{width:8px;height:8px;border-radius:50%;background:#e55b63}
</style>
