<template>
  <view class="page-shell"><view v-if="data" class="page-content"><view class="balance-card"><text class="eyebrow">商户可结算余额</text><text class="balance">¥{{ money(data.summary.availableAmount) }}</text><view class="balance-meta"><text>商户累计收入 ¥{{ money(data.summary.merchantIncome) }}</text><text>冻结 ¥{{ money(data.summary.frozenAmount) }}</text></view><button :disabled="!data.summary.availableAmount" @click="withdraw">申请结算</button></view><view class="stats-grid"><view><text>¥{{ money(data.summary.grossAmount) }}</text><text>订单净额</text></view><view><text>¥{{ money(data.summary.caregiverCommission) }}</text><text>护理佣金</text></view><view><text>¥{{ money(data.summary.platformFee) }}</text><text>平台服务费</text></view></view><view class="section-head"><text>订单分账</text></view><view v-for="item in data.list" :key="item.settlementId" class="record-card"><view><text class="record-title">{{ item.serviceItemName }} · {{ item.caregiverName }}</text><text class="record-meta">{{ item.orderNo }} · 净额 ¥{{ money(item.netAmount) }}</text><text v-if="item.freezeReason" class="freeze-reason">{{ item.freezeReason }}</text></view><view class="record-amount"><text>商户 ¥{{ money(item.merchantIncome) }}</text><text :class="`tone-${getSettlementStatusMeta(item.status).tone}`">{{ getSettlementStatusMeta(item.status).label }}</text></view></view><view class="section-head"><text>结算记录</text></view><view v-for="item in data.withdrawals" :key="item.withdrawalId" class="record-card"><view><text class="record-title">{{ item.accountName }}</text><text class="record-meta">{{ item.accountNo }} · {{ formatTime(item.applyTime) }}</text></view><view class="record-amount"><text>¥{{ money(item.amount) }}</text><text>{{ withdrawalText(item.status) }}</text></view></view></view><view v-else class="loading"><u-loading-icon size="30" color="#00A89D" /></view></view>
</template>
<script setup>
import { computed } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getSettlementStatusMeta } from '@/constants/settlement.js'
import { ROLES } from '@/constants/roles.js'
import { useSettlementStore } from '@/store/settlement.js'
import { requireRole } from '@/utils/permission.js'
const store = useSettlementStore(); const data = computed(() => store.merchantSettlements); onShow(() => { if (requireRole(ROLES.MERCHANT_MEMBER)) store.fetchMerchantSettlements() }); function money(value) { return Number(value || 0).toFixed(2) } function formatTime(value) { return value?.replace('T',' ').replace('+08:00','').slice(0,16) || '--' } function withdrawalText(status) { return ({ PROCESSING: '结算中', SUCCESS: '已到账', REJECTED: '已驳回' }[status] || status) } function withdraw() { uni.showModal({ title: '申请结算', editable: true, placeholderText: `最多可结算 ${money(data.value.summary.availableAmount)} 元`, success: async ({ confirm, content }) => { if (!confirm) return; const amount = Number(content); if (!amount || amount <= 0) return uni.showToast({ title: '请输入正确的结算金额', icon: 'none' }); await store.applyMerchantWithdrawal({ amount, accountName: '北京康宁护理服务有限公司', accountNo: '建设银行 ****1234' }); uni.showToast({ title: '结算申请已提交', icon: 'success' }) } }) }
</script>
<style lang="scss" scoped>
.page-shell{min-height:100vh;background:$page-gradient}.page-content{padding:24rpx $spacing-base 60rpx}.balance-card{padding:30rpx;border-radius:31rpx;color:#fff;background:linear-gradient(135deg,#116b68,#00a89d 55%,#38c6b5);box-shadow:$shadow-float}.eyebrow,.balance,.balance-meta text,.stats-grid text,.record-title,.record-meta,.record-amount text,.freeze-reason{display:block}.eyebrow{font-size:$font-size-xs;opacity:.78}.balance{margin-top:10rpx;font-size:55rpx;font-weight:800}.balance-meta{display:flex;gap:24rpx;margin-top:11rpx;font-size:$font-size-xs;opacity:.82}.balance-card button{height:65rpx;margin:24rpx 0 0;border:0;border-radius:$radius-round;color:#008d84;background:#fff;line-height:65rpx}.balance-card button::after{border:0}.stats-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11rpx;margin-top:18rpx}.stats-grid view{padding:20rpx 5rpx;border:$glass-border-soft;border-radius:21rpx;background:#fff;text-align:center}.stats-grid text:first-child{color:$text-color;font-size:$font-size-base;font-weight:700}.stats-grid text:last-child{margin-top:5rpx;color:$text-color-hint;font-size:19rpx}.section-head{margin:27rpx 4rpx 14rpx;color:$text-color;font-size:$font-size-md;font-weight:700}.record-card{display:flex;align-items:center;justify-content:space-between;gap:15rpx;margin-top:12rpx;padding:21rpx;border:$glass-border-soft;border-radius:24rpx;background:$surface-gradient;box-shadow:$shadow-sm}.record-title{color:$text-color;font-size:$font-size-sm;font-weight:700}.record-meta{margin-top:6rpx;color:$text-color-hint;font-size:$font-size-xs}.freeze-reason{margin-top:6rpx;color:$warning-color;font-size:20rpx}.record-amount{text-align:right}.record-amount text:first-child{color:$success-color;font-size:$font-size-sm;font-weight:700}.record-amount text:last-child{margin-top:5rpx;color:$text-color-hint;font-size:$font-size-xs}.record-amount .tone-warning{color:$warning-color}.record-amount .tone-primary{color:$primary-color}.record-amount .tone-success{color:$success-color}.loading{display:flex;justify-content:center;padding:180rpx 0}
</style>
