<template>
  <div v-loading="loading" class="review-detail-page"><div class="detail-nav"><el-button text @click="router.back()"><el-icon><ArrowLeft /></el-icon>返回列表</el-button><el-tag v-if="detail" :type="detail.status === 'RESOLVED' ? 'success' : 'danger'" round>{{ statusText(detail.status) }}</el-tag></div><template v-if="detail"><section class="detail-hero"><div class="hero-avatar" style="background:#e7833b">异</div><div class="hero-copy"><span>{{ detail.typeText }} · {{ detail.exceptionNo }}</span><h2>{{ detail.title }}</h2><p>{{ detail.description }}</p></div><div class="hero-meta"><span>所属商户</span><strong>{{ detail.merchantName }}</strong><span>发生时间</span><strong>{{ detail.createTime }}</strong></div></section><section class="detail-layout"><div class="detail-main"><article class="panel detail-panel"><div class="panel-head"><div><span>关联订单</span><h3>订单和异常信息</h3></div></div><div class="field-table"><div v-for="field in detail.fields" :key="field.label" :class="{ wide: field.wide }"><span>{{ field.label }}</span><strong>{{ field.value }}</strong></div></div></article><article class="panel detail-panel"><div class="panel-head"><div><span>凭证材料</span><h3>商户与护理人员提交内容</h3></div></div><div class="document-grid"><div v-for="item in detail.evidence" :key="item.name" class="document-card"><div class="document-preview"><span>凭证</span><b>已提交</b></div><strong>{{ item.name }}</strong><span>{{ item.value }}</span></div></div></article></div><aside class="detail-side"><article class="panel timeline-panel"><div class="panel-head"><div><span>处理记录</span><h3>异常时间线</h3></div></div><el-timeline><el-timeline-item v-for="record in detail.records" :key="record.id" :timestamp="record.time" placement="top"><strong>{{ record.title }}</strong><p>{{ record.remark }}</p><small>{{ record.operator }}</small></el-timeline-item></el-timeline></article><article v-if="detail.status === 'ADMIN_REVIEW'" class="action-panel"><strong>平台处理</strong><p>核验商户和护理人员提交的记录后，选择结案或批准退款。</p><el-button type="success" size="large" @click="process('resolve')">确认结案</el-button><el-button type="warning" size="large" @click="process('approve-refund')">批准退款</el-button></article></aside></section></template></div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useExceptionStore } from '../../stores/exception.js'
const route = useRoute(); const router = useRouter(); const store = useExceptionStore(); const loading = ref(true); const detail = computed(() => store.currentException); onMounted(async () => { try { await store.fetchExceptionDetail(route.params.id) } finally { loading.value = false } }); function statusText(value) { return ({ ADMIN_REVIEW: '平台复核', RESOLVED: '已解决', MERCHANT_PROCESSING: '商户处理中' }[value] || value) } async function process(action) { const { value } = await ElMessageBox.prompt('请填写处理结论和依据', action === 'resolve' ? '确认结案' : '批准退款', { inputValue: action === 'resolve' ? '资料核验完成，异常工单结案' : '同意按订单已支付金额执行退款', inputValidator: (text) => text.trim().length >= 10 || '至少填写10个字符' }); await store.processException(detail.value.exceptionId, action, value.trim()); ElMessage.success('异常工单已处理') }
</script>
