<template>
  <div class="review-list-page"><section class="page-intro"><div><span class="page-eyebrow">EXCEPTION CENTER</span><h2>异常订单监管</h2><p>监管异常签到、无人可派、接单超时和退款建议。</p></div><div class="intro-count"><strong>{{ store.total }}</strong><span>条异常</span></div></section><section class="panel filter-panel"><el-segmented v-model="status" :options="options" @change="load" /><el-button type="primary" @click="load">刷新列表</el-button></section><section class="panel table-panel"><el-table v-loading="store.loading" :data="store.exceptions" row-class-name="clickable-row" @row-click="goDetail"><el-table-column prop="typeText" label="异常类型" width="150" /><el-table-column prop="title" label="异常事项" min-width="220" /><el-table-column prop="merchantName" label="所属商户" min-width="150" /><el-table-column prop="orderNo" label="订单编号" width="170" /><el-table-column prop="createTime" label="发生时间" width="170" /><el-table-column label="状态" width="120"><template #default="{ row }"><el-tag :type="row.status === 'ADMIN_REVIEW' ? 'danger' : row.status === 'RESOLVED' ? 'success' : 'warning'" round>{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link type="primary" @click.stop="goDetail(row)">处理</el-button></template></el-table-column></el-table></section></div>
</template>
<script setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useExceptionStore } from '../../stores/exception.js'
const router = useRouter(); const store = useExceptionStore(); const status = ref('ADMIN_REVIEW'); const options = [{ label: '全部', value: '' }, { label: '平台复核', value: 'ADMIN_REVIEW' }, { label: '处理中', value: 'MERCHANT_PROCESSING' }, { label: '已解决', value: 'RESOLVED' }]; function load() { return store.fetchExceptions(status.value ? { status: status.value } : {}) } function goDetail(row) { router.push(`/exceptions/${row.exceptionId}`) } function statusText(value) { return ({ OPEN: '待处理', MERCHANT_PROCESSING: '商户处理中', ADMIN_REVIEW: '平台复核', RESOLVED: '已解决' }[value] || value) } watch(status, load, { immediate: true })
</script>
