<template>
  <view class="page-shell"><view v-if="data" class="page-content"><view class="balance-card"><text class="eyebrow">可提现佣金</text><text class="balance">¥{{ money(data.summary.availableAmount) }}</text><view class="balance-meta"><text>累计佣金 ¥{{ money(data.summary.totalCommission) }}</text><text>冻结 ¥{{ money(data.summary.frozenAmount) }}</text></view><button :disabled="!data.summary.availableAmount" @click="withdraw">申请提现</button></view><view class="rule-card"><text>当前演示分账</text><text>护理人员 {{ percent(data.splitRule.caregiverRate) }}</text><text>商户 {{ percent(data.splitRule.merchantRate) }}</text><text>平台 {{ percent(data.splitRule.platformRate) }}</text></view><view class="section-head"><text>佣金明细</text></view><view v-for="item in data.list" :key="item.settlementId" class="record-card"><view><text class="record-title">{{ item.serviceItemName }}</text><text class="record-meta">{{ item.serviceDate }} · {{ item.orderNo }}</text></view><view class="record-amount"><text>+¥{{ money(item.caregiverCommission) }}</text><text :class="`tone-${getSettlementStatusMeta(item.status).tone}`">{{ getSettlementStatusMeta(item.status).label }}</text></view></view><view class="section-head"><text>提现记录</text></view><view v-for="item in data.withdrawals" :key="item.withdrawalId" class="record-card"><view><text class="record-title">{{ item.accountNo }}</text><text class="record-meta">{{ formatTime(item.applyTime) }}</text></view><view class="record-amount"><text>-¥{{ money(item.amount) }}</text><text>{{ withdrawalText(item.status) }}</text></view></view></view><view v-else class="loading"><u-loading-icon size="30" color="#3A7BF7" /></view></view>
</template>
<script setup>
import { computed } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getSettlementStatusMeta } from '@/constants/settlement.js'
import { ROLES } from '@/constants/roles.js'
import { useSettlementStore } from '@/store/settlement.js'
import { requireRole } from '@/utils/permission.js'
const store = useSettlementStore(); const data = computed(() => store.caregiverEarnings); onShow(() => { if (requireRole(ROLES.CAREGIVER)) store.fetchCaregiverEarnings() }); function money(value) { return Number(value || 0).toFixed(2) } function percent(value) { return `${Math.round(Number(value || 0) * 100)}%` } function formatTime(value) { return value?.replace('T',' ').replace('+08:00','').slice(0,16) || '--' } function withdrawalText(status) { return ({ PROCESSING: '处理中', SUCCESS: '已到账', REJECTED: '已驳回' }[status] || status) } function withdraw() { uni.showModal({ title: '申请提现', editable: true, placeholderText: `最多可提现 ${money(data.value.summary.availableAmount)} 元`, success: async ({ confirm, content }) => { if (!confirm) return; const amount = Number(content); if (!amount || amount <= 0) return uni.showToast({ title: '请输入正确的提现金额', icon: 'none' }); await store.applyCaregiverWithdrawal({ amount, accountName: '王护理员', accountNo: '支付宝 138****8000' }); uni.showToast({ title: '提现申请已提交', icon: 'success' }) } }) }
</script>
<style lang="scss" scoped>
.page-shell{min-height:100vh;background:$page-gradient}.page-content{padding:24rpx $spacing-base 60rpx}.balance-card{padding:30rpx;border-radius:31rpx;color:#fff;background:linear-gradient(135deg,#245ddc,#3a7bf7 55%,#00b8d8);box-shadow:$shadow-float}.eyebrow,.balance,.balance-meta text,.rule-card text,.record-title,.record-meta,.record-amount text{display:block}.eyebrow{font-size:$font-size-xs;opacity:.78}.balance{margin-top:10rpx;font-size:55rpx;font-weight:800}.balance-meta{display:flex;gap:24rpx;margin-top:11rpx;font-size:$font-size-xs;opacity:.82}.balance-card button{height:65rpx;margin:24rpx 0 0;border:0;border-radius:$radius-round;color:$primary-color;background:#fff;line-height:65rpx}.balance-card button::after{border:0}.rule-card{display:grid;grid-template-columns:1.5fr repeat(3,1fr);margin-top:18rpx;padding:19rpx;border-radius:22rpx;color:$text-color-secondary;background:#fff;font-size:$font-size-xs;text-align:center}.rule-card text:first-child{text-align:left;font-weight:700}.section-head{margin:27rpx 4rpx 14rpx;color:$text-color;font-size:$font-size-md;font-weight:700}.record-card{display:flex;align-items:center;justify-content:space-between;gap:15rpx;margin-top:12rpx;padding:21rpx;border:$glass-border-soft;border-radius:24rpx;background:$surface-gradient;box-shadow:$shadow-sm}.record-title{color:$text-color;font-size:$font-size-sm;font-weight:700}.record-meta{margin-top:6rpx;color:$text-color-hint;font-size:$font-size-xs}.record-amount{text-align:right}.record-amount text:first-child{color:$success-color;font-size:$font-size-base;font-weight:700}.record-amount text:last-child{margin-top:5rpx;color:$text-color-hint;font-size:$font-size-xs}.record-amount .tone-warning{color:$warning-color}.record-amount .tone-primary{color:$primary-color}.record-amount .tone-success{color:$success-color}.loading{display:flex;justify-content:center;padding:180rpx 0}
</style>
