<template>
  <view v-if="preview" class="page-shell"><view class="rule-card" :class="{ blocked: !preview.cancellable }"><view class="rule-icon"><u-icon :name="preview.cancellable ? 'rmb-circle-fill' : 'info-circle-fill'" size="34" color="#FFFFFF" /></view><view><text class="rule-title">{{ preview.ruleTitle }}</text><text class="rule-desc">{{ preview.ruleDescription }}</text></view></view><view class="amount-card"><view class="amount-row"><text>订单金额</text><text>¥{{ preview.totalAmount }}</text></view><view class="amount-row"><text>扣除金额</text><text class="deduction">- ¥{{ preview.deductionAmount }}</text></view><view class="amount-row total"><text>预计退款</text><text>¥{{ preview.refundAmount }}</text></view></view><view v-if="preview.cancellable" class="form-card"><text class="section-title">取消原因</text><view class="reason-grid"><text v-for="option in reasons" :key="option" :class="{ active: reason === option }" @click="reason = option">{{ option }}</text></view><textarea v-model="remark" maxlength="200" class="remark-input" placeholder="可以补充说明具体原因" /></view><view class="notice"><u-icon name="info-circle" size="18" color="#8E9DAE" /><text>退款金额和规则以服务阶段为准。Mock 约 8 秒后完成退款，真实环境以后端支付渠道结果为准。</text></view><button v-if="preview.cancellable" class="submit-button" :disabled="submitting" @click="submit">{{ submitting ? '提交中...' : '确认取消订单' }}</button><button v-else class="back-button" @click="uni.navigateBack()">返回订单详情</button></view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { useAftersalesStore } from '@/store/aftersales.js'
const store = useAftersalesStore(); const orderId = ref(null); const reason = ref('计划有变'); const remark = ref(''); const submitting = ref(false); const preview = computed(() => store.cancelPreview); const reasons = ['计划有变', '服务时间不合适', '地址填写错误', '等待时间过长', '其他原因']; onLoad(async (options) => { orderId.value = Number(options.id); await store.previewCancellation(orderId.value) }); async function submit() { submitting.value = true; try { await store.cancelOrder(orderId.value, `${reason.value}${remark.value.trim() ? `：${remark.value.trim()}` : ''}`); uni.showToast({ title: preview.value.refundAmount > 0 ? '取消成功，退款处理中' : '订单已取消', icon: 'success' }); setTimeout(() => uni.redirectTo({ url: `/pages/order/order-detail?id=${orderId.value}` }), 700) } finally { submitting.value = false } }
</script>
<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 24rpx $spacing-base 70rpx; background: $page-gradient; }.rule-card { display: flex; align-items: center; gap: 18rpx; min-height: 170rpx; padding: 27rpx; border-radius: 30rpx; color: #fff; background: linear-gradient(135deg,#e7833b,#f4a259); box-shadow: $shadow-float; }.rule-card.blocked { background: linear-gradient(135deg,#66788c,#8e9dae); }.rule-icon { display: flex; align-items: center; justify-content: center; width: 74rpx; height: 74rpx; flex-shrink: 0; border-radius: 24rpx; background: rgba(255,255,255,.18); }.rule-title,.rule-desc { display: block; }.rule-title { font-size: 32rpx; font-weight: 700; }.rule-desc { margin-top: 8rpx; font-size: $font-size-xs; line-height: 1.6; opacity: .84; }.amount-card,.form-card { margin-top: 19rpx; padding: 25rpx; border: $glass-border-soft; border-radius: 27rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.amount-row { display: flex; justify-content: space-between; padding: 16rpx 0; border-bottom: 1rpx solid $divider-color; color: $text-color-secondary; font-size: $font-size-sm; }.amount-row:last-child { border-bottom: 0; }.amount-row.total { color: $text-color; font-size: $font-size-base; font-weight: 700; }.amount-row.total text:last-child { color: $warning-color; font-size: 35rpx; }.deduction { color: $error-color; }.section-title { color: $text-color; font-size: $font-size-md; font-weight: 700; }.reason-grid { display: flex; flex-wrap: wrap; gap: 10rpx; margin-top: 17rpx; }.reason-grid text { padding: 10rpx 16rpx; border-radius: $radius-round; color: $text-color-hint; background: $bg-color-grey; font-size: $font-size-xs; }.reason-grid text.active { color: $primary-color; background: $primary-bg; }.remark-input { width: 100%; height: 140rpx; margin-top: 17rpx; padding: 16rpx; border: 1rpx solid $border-color; border-radius: 19rpx; background: rgba(255,255,255,.7); font-size: $font-size-sm; }.notice { display: flex; gap: 10rpx; margin-top: 18rpx; padding: 18rpx; border-radius: 20rpx; color: $text-color-hint; background: rgba(240,243,247,.78); font-size: $font-size-xs; line-height: 1.55; }.submit-button,.back-button { width: 100%; height: 82rpx; margin-top: 22rpx; border: 0; border-radius: $radius-round; line-height: 82rpx; }.submit-button { color: #fff; background: linear-gradient(135deg,#e7833b,#f4a259); }.back-button { color: $primary-color; background: $primary-bg; }.submit-button::after,.back-button::after { border: 0; }
</style>
