<template>
  <view class="page-shell"><view class="hero"><view><text class="eyebrow">异常中心</text><text class="title">待处理 {{ openCount }} 项</text><text class="subtitle">接单超时、无人可派和异常签到统一在此处理</text></view><u-icon name="warning-fill" size="37" color="#FFFFFF" /></view><scroll-view scroll-x class="filter-scroll"><view class="filters"><text v-for="item in filters" :key="item.value" :class="{ active: status === item.value }" @click="changeFilter(item.value)">{{ item.label }}</text></view></scroll-view><view v-if="store.loading" class="loading"><u-loading-icon size="28" color="#FF8A5C" /></view><view v-else><view v-for="item in store.exceptions" :key="item.exceptionId" class="exception-card" @click="goDetail(item.exceptionId)"><view class="card-head"><text class="type">{{ getExceptionTypeMeta(item.type).label }}</text><text class="status">{{ statusText(item.status) }}</text></view><text class="service">{{ item.serviceItemName }} · {{ item.receiverName }}</text><text class="desc">{{ item.description }}</text><view class="card-foot"><text>{{ formatTime(item.createTime) }}</text><text>{{ item.orderNo }} ›</text></view></view><empty-state v-if="!store.exceptions.length" title="暂无异常工单" description="调度和签到异常会显示在这里" /></view></view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import EmptyState from '@/components/base/empty-state.vue'
import { EXCEPTION_STATUS, getExceptionTypeMeta } from '@/constants/aftersales-status.js'
import { ROLES } from '@/constants/roles.js'
import { useAftersalesStore } from '@/store/aftersales.js'
import { requireRole } from '@/utils/permission.js'
const store = useAftersalesStore(); const status = ref(''); const filters = [{ label: '全部', value: '' }, { label: '待处理', value: EXCEPTION_STATUS.OPEN }, { label: '商户处理中', value: EXCEPTION_STATUS.MERCHANT_PROCESSING }, { label: '平台复核', value: EXCEPTION_STATUS.ADMIN_REVIEW }, { label: '已解决', value: EXCEPTION_STATUS.RESOLVED }]; const openCount = computed(() => store.exceptions.filter((item) => ![EXCEPTION_STATUS.RESOLVED, EXCEPTION_STATUS.CLOSED].includes(item.status)).length); onShow(async () => { if (!requireRole(ROLES.MERCHANT_MEMBER)) return; await load() }); function load() { return store.fetchMerchantExceptions(status.value ? { status: status.value } : {}) } function changeFilter(value) { status.value = value; load() } function statusText(value) { return ({ OPEN: '待处理', MERCHANT_PROCESSING: '商户处理中', ADMIN_REVIEW: '平台复核', RESOLVED: '已解决', CLOSED: '已关闭' }[value] || value) } function formatTime(value) { return value?.replace('T', ' ').replace('+08:00', '').slice(0, 16) || '--' } function goDetail(id) { uni.navigateTo({ url: `/subpkg-merchant/exception-detail/index?id=${id}` }) }
</script>
<style lang="scss" scoped>
.page-shell { min-height:100vh;padding:24rpx $spacing-base 70rpx;background:$page-gradient; }.hero { display:flex;align-items:center;justify-content:space-between;min-height:190rpx;padding:29rpx;border-radius:31rpx;color:#fff;background:linear-gradient(135deg,#d56b34,#f29a55);box-shadow:$shadow-float; }.eyebrow,.title,.subtitle { display:block; }.eyebrow { font-size:$font-size-xs;opacity:.75; }.title { margin-top:7rpx;font-size:38rpx;font-weight:700; }.subtitle { margin-top:8rpx;font-size:$font-size-xs;opacity:.84; }.filter-scroll { margin-top:18rpx;white-space:nowrap; }.filters { display:flex;gap:10rpx; }.filters text { padding:11rpx 18rpx;border-radius:$radius-round;color:$text-color-hint;background:rgba(255,255,255,.76);font-size:$font-size-xs; }.filters text.active { color:#fff;background:linear-gradient(135deg,#e7833b,#f4a259); }.loading { display:flex;justify-content:center;padding:150rpx 0; }.exception-card { margin-top:15rpx;padding:22rpx;border:$glass-border-soft;border-radius:26rpx;background:$surface-gradient;box-shadow:$shadow-sm; }.card-head,.card-foot { display:flex;align-items:center;justify-content:space-between; }.type { color:$warning-color;font-size:$font-size-sm;font-weight:700; }.status { padding:5rpx 10rpx;border-radius:$radius-round;color:$warning-color;background:#fff4ea;font-size:20rpx; }.service,.desc { display:block; }.service { margin-top:15rpx;color:$text-color;font-size:$font-size-base;font-weight:700; }.desc { margin-top:7rpx;color:$text-color-secondary;font-size:$font-size-xs;line-height:1.55; }.card-foot { margin-top:17rpx;padding-top:15rpx;border-top:1rpx solid $divider-color;color:$text-color-disabled;font-size:21rpx; }
</style>
