<template>
  <div v-loading="loading" class="review-detail-page"><div class="detail-nav"><el-button text @click="router.back()"><el-icon><ArrowLeft /></el-icon>返回列表</el-button><el-tag v-if="detail" :type="detail.status === 2 ? 'success' : 'danger'" round>{{ statusText(detail.status) }}</el-tag></div><template v-if="detail"><section class="detail-hero"><div class="hero-avatar complaint-avatar">诉</div><div class="hero-copy"><span>{{ detail.typeText }} · {{ detail.complaintNo }}</span><h2>{{ detail.content }}</h2><p>{{ detail.serviceItemName }} · {{ detail.orderNo }}</p></div><div class="hero-meta"><span>所属商户</span><strong>{{ detail.merchantName }}</strong><span>提交时间</span><strong>{{ detail.createTime }}</strong></div></section><section class="detail-layout"><div class="detail-main"><article class="panel detail-panel"><div class="panel-head"><div><span>争议材料</span><h3>顾客与商户陈述</h3></div></div><div class="statement-block customer"><strong>顾客诉求</strong><p>{{ detail.content }}</p></div><div class="statement-block merchant"><strong>商户说明</strong><p>{{ detail.merchantStatement || '商户尚未提交说明' }}</p></div></article><article class="panel detail-panel"><div class="panel-head"><div><span>凭证材料</span><h3>双方提交证据</h3></div></div><div class="document-grid"><div v-for="item in allEvidence" :key="item.name" class="document-card"><div class="document-preview"><span>证</span><b>{{ item.side }}</b></div><strong>{{ item.name }}</strong><span>{{ item.value }}</span></div></div></article></div><aside class="detail-side"><article class="panel timeline-panel"><div class="panel-head"><div><span>处理记录</span><h3>投诉时间线</h3></div></div><el-timeline><el-timeline-item v-for="record in detail.tracks" :key="record.trackId" :timestamp="record.createTime" placement="top"><strong>{{ record.operator }}</strong><p>{{ record.content }}</p></el-timeline-item></el-timeline></article><article v-if="detail.status === 4" class="action-panel"><strong>平台仲裁</strong><p>选择退款方案并填写事实依据。退款金额不得超过订单金额。</p><el-select v-model="form.decision" size="large"><el-option label="不予退款" value="NO_REFUND" /><el-option label="部分退款" value="PARTIAL_REFUND" /><el-option label="全额退款" value="FULL_REFUND" /></el-select><el-input-number v-if="form.decision === 'PARTIAL_REFUND'" v-model="form.refundAmount" :min="0" :max="detail.totalAmount" controls-position="right" /><el-input v-model="form.remark" type="textarea" :rows="4" placeholder="填写裁决事实和处理依据" /><el-button type="primary" size="large" @click="submit">确认裁决</el-button></article><article v-else-if="detail.decision" class="result-panel success"><strong>{{ detail.decision.label }}</strong><p>{{ detail.decision.remark }}</p><span>退款金额 ¥{{ detail.decision.refundAmount || 0 }}</span></article></aside></section></template></div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useComplaintStore } from '../../stores/complaint.js'
const route = useRoute(); const router = useRouter(); const store = useComplaintStore(); const loading = ref(true); const detail = computed(() => store.currentComplaint); const form = reactive({ decision: 'NO_REFUND', refundAmount: 0, remark: '' }); const allEvidence = computed(() => [...(detail.value?.customerEvidence || []).map((item) => ({ ...item, side: '顾客' })), ...(detail.value?.merchantEvidence || []).map((item) => ({ ...item, side: '商户' }))]); onMounted(async () => { try { await store.fetchComplaintDetail(route.params.id) } finally { loading.value = false } }); function statusText(value) { return ({ 2: '已裁决', 4: '平台仲裁' }[value] || value) } async function submit() { if (form.remark.trim().length < 10) return ElMessage.warning('裁决依据至少填写10个字符'); const refundAmount = form.decision === 'FULL_REFUND' ? Number(detail.value.totalAmount) : form.decision === 'PARTIAL_REFUND' ? Number(form.refundAmount) : 0; await store.arbitrateComplaint(detail.value.complaintId, { decision: form.decision, refundAmount, remark: form.remark.trim() }); ElMessage.success('投诉仲裁已完成') }
</script>
<style scoped>
.complaint-avatar{background:#e7833b}.statement-block{margin-top:18px;padding:18px;border-radius:15px}.statement-block strong{font-size:13px}.statement-block p{margin:8px 0 0;color:#68728a;font-size:12px;line-height:1.7}.statement-block.customer{background:#fff6ef}.statement-block.merchant{background:#eff5ff}.action-panel .el-select,.action-panel .el-input-number,.action-panel .el-textarea{width:100%;margin-top:12px}
</style>
