<template>
  <div class="review-list-page"><section class="page-intro"><div><span class="page-eyebrow">COMPLAINT ARBITRATION</span><h2>投诉仲裁</h2><p>核验顾客诉求、商户说明和履约凭证，形成可追溯裁决。</p></div><div class="intro-count"><strong>{{ store.total }}</strong><span>条投诉</span></div></section><section class="panel filter-panel"><el-segmented v-model="status" :options="options" /><el-button type="primary" @click="load">刷新列表</el-button></section><section class="panel table-panel"><el-table v-loading="store.loading" :data="store.complaints" row-class-name="clickable-row" @row-click="goDetail"><el-table-column prop="typeText" label="投诉类型" width="130" /><el-table-column prop="content" label="顾客诉求" min-width="240" show-overflow-tooltip /><el-table-column prop="merchantName" label="所属商户" min-width="150" /><el-table-column prop="orderNo" label="订单编号" width="170" /><el-table-column prop="updateTime" label="更新时间" width="170" /><el-table-column label="状态" width="120"><template #default="{ row }"><el-tag :type="row.status === 4 ? 'danger' : row.status === 2 ? 'success' : 'warning'" round>{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link type="primary" @click.stop="goDetail(row)">仲裁</el-button></template></el-table-column></el-table></section></div>
</template>
<script setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useComplaintStore } from '../../stores/complaint.js'
const router = useRouter(); const store = useComplaintStore(); const status = ref(0); const options = [{ label: '全部', value: '' }, { label: '待处理', value: 0 }, { label: '处理中', value: 1 }, { label: '已解决', value: 2 }, { label: '已关闭', value: 3 }]; function load() { return store.fetchComplaints(status.value === '' ? {} : { status: status.value }) } function goDetail(row) { router.push(`/complaints/${row.id}`) } function statusText(value) { return ({ 0: '待处理', 1: '处理中', 2: '已解决', 3: '已关闭' }[value] || value) } watch(status, load, { immediate: true })
</script>
