<template>
  <view class="page-shell"><view class="hero"><view><text class="eyebrow">消息中心</text><text class="title">{{ roleLabel }}消息</text><text class="subtitle">{{ store.unreadCount ? `${store.unreadCount} 条未读消息` : '所有消息均已阅读' }}</text></view><view class="hero-icon"><u-icon name="bell-fill" size="35" color="#FFFFFF" /></view></view><view class="toolbar"><scroll-view scroll-x class="category-scroll"><view class="categories"><text v-for="item in categories" :key="item.value" :class="{ active: category === item.value }" @click="changeCategory(item.value)">{{ item.label }}</text></view></scroll-view><text v-if="store.unreadCount" class="read-all" @click="readAll">全部已读</text></view><view v-if="store.loading" class="loading"><u-loading-icon size="29" color="#3A7BF7" /></view><view v-else><view v-for="item in store.notifications" :key="item.notificationId" class="notification-card" :class="{ unread: !item.read }" @click="open(item)"><view class="category-icon" :style="{ background: `${meta(item.category).color}18` }"><u-icon :name="meta(item.category).icon" size="23" :color="meta(item.category).color" /></view><view class="notification-copy"><view class="title-row"><text class="notification-title">{{ item.title }}</text><view v-if="!item.read" class="unread-dot" /></view><text class="notification-content">{{ item.content }}</text><view class="notification-foot"><text>{{ meta(item.category).label }}</text><text>{{ formatTime(item.createTime) }}</text></view></view><u-icon v-if="item.target" name="arrow-right" size="15" color="#C5CDD8" /></view><empty-state v-if="!store.notifications.length" title="暂无消息" description="订单、审核和服务状态变化会通知你" /></view></view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad, onShow } from '@dcloudio/uni-app'
import EmptyState from '@/components/base/empty-state.vue'
import { NOTIFICATION_CATEGORY, getNotificationCategoryMeta } from '@/constants/notification.js'
import { getRoleLabel } from '@/constants/roles.js'
import { useNotificationStore } from '@/store/notification.js'
import { getActiveRole } from '@/utils/storage.js'
const store = useNotificationStore(); const category = ref(''); const categories = [{ label: '全部', value: '' }, { label: '订单履约', value: NOTIFICATION_CATEGORY.ORDER }, { label: '派单', value: NOTIFICATION_CATEGORY.ASSIGNMENT }, { label: '审核', value: NOTIFICATION_CATEGORY.REVIEW }, { label: '退款', value: NOTIFICATION_CATEGORY.REFUND }, { label: '异常', value: NOTIFICATION_CATEGORY.EXCEPTION }, { label: '投诉', value: NOTIFICATION_CATEGORY.COMPLAINT }]; const roleLabel = computed(() => getRoleLabel(getActiveRole())); onLoad((options) => { if (options.category) category.value = options.category }); onShow(load); function load() { return store.fetchNotifications(category.value ? { category: category.value } : {}) } function changeCategory(value) { category.value = value; load() } function meta(value) { return getNotificationCategoryMeta(value) } function formatTime(value) { return value?.replace('T',' ').replace('+08:00','').slice(0,16) || '--' } async function readAll() { await store.markAllAsRead(); uni.showToast({ title: '已全部标为已读', icon: 'success' }) } async function open(item) { if (!item.read) await store.markAsRead(item.notificationId); const target = item.target || {}; const routes = { CUSTOMER_ORDER: `/pages/order/order-detail?id=${target.id}`, CUSTOMER_COMPLAINT: `/pages/complaint/complaint-detail?id=${target.id}`, CAREGIVER_TASK: `/subpkg-caregiver/task-detail/index?id=${target.id}`, MERCHANT_ORDER: `/subpkg-merchant/order-detail/index?id=${target.id}`, MERCHANT_EXCEPTION: `/subpkg-merchant/exception-detail/index?id=${target.id}`, MERCHANT_COMPLAINT: `/subpkg-merchant/complaint-detail/index?id=${target.id}`, MERCHANT_SERVICES: '/subpkg-merchant/services/index', CAREGIVER_PROFILE: '/subpkg-caregiver/profile/index', MERCHANT_PROFILE: '/subpkg-merchant/profile/index' }; const url = routes[target.type]; if (url) uni.navigateTo({ url }); else if (target.type) uni.showToast({ title: '该消息暂无可打开页面', icon: 'none' }) }
</script>
<style lang="scss" scoped>
.page-shell{min-height:100vh;padding:24rpx $spacing-base 60rpx;background:$page-gradient}.hero{display:flex;align-items:center;justify-content:space-between;padding:29rpx;border-radius:31rpx;color:#fff;background:$primary-gradient;box-shadow:$shadow-float}.eyebrow,.title,.subtitle,.notification-title,.notification-content{display:block}.eyebrow{font-size:$font-size-xs;opacity:.76}.title{margin-top:7rpx;font-size:34rpx;font-weight:700}.subtitle{margin-top:7rpx;font-size:$font-size-xs;opacity:.84}.hero-icon{display:flex;align-items:center;justify-content:center;width:82rpx;height:82rpx;border-radius:25rpx;background:rgba(255,255,255,.18)}.toolbar{display:flex;align-items:center;gap:12rpx;margin:19rpx 0}.category-scroll{flex:1;white-space:nowrap}.categories{display:flex;gap:9rpx}.categories text{padding:11rpx 18rpx;border-radius:$radius-round;color:$text-color-hint;background:#fff;font-size:$font-size-xs}.categories text.active{color:#fff;background:$primary-color}.read-all{flex-shrink:0;color:$primary-color;font-size:$font-size-xs}.notification-card{display:flex;align-items:center;gap:15rpx;margin-top:14rpx;padding:22rpx;border:1rpx solid transparent;border-radius:26rpx;background:rgba(255,255,255,.72);box-shadow:$shadow-sm}.notification-card.unread{border-color:rgba(58,123,247,.16);background:#fff}.category-icon{display:flex;align-items:center;justify-content:center;width:68rpx;height:68rpx;flex-shrink:0;border-radius:21rpx}.notification-copy{min-width:0;flex:1}.title-row{display:flex;align-items:center;gap:9rpx}.notification-title{overflow:hidden;color:$text-color;font-size:$font-size-sm;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.unread-dot{width:12rpx;height:12rpx;flex-shrink:0;border-radius:50%;background:$error-color}.notification-content{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;margin-top:8rpx;color:$text-color-secondary;font-size:$font-size-xs;line-height:1.6}.notification-foot{display:flex;gap:16rpx;margin-top:10rpx;color:$text-color-disabled;font-size:20rpx}.loading{display:flex;justify-content:center;padding:140rpx 0}
</style>
