<template>
  <view class="page-shell"><view class="hero"><view><text class="eyebrow">投诉协同</text><text class="title">待响应 {{ pendingCount }} 项</text><text class="subtitle">查看顾客诉求，提交商户说明和履约凭证</text></view><u-icon name="chat-fill" size="36" color="#FFFFFF" /></view><scroll-view scroll-x class="filter-scroll"><view class="filters"><text v-for="item in filters" :key="item.value" :class="{ active: status === item.value }" @click="changeFilter(item.value)">{{ item.label }}</text></view></scroll-view><view v-if="store.loading" class="loading"><u-loading-icon size="28" color="#FF8A5C" /></view><view v-else><view v-for="item in store.merchantComplaints" :key="item.complaintId" class="complaint-card" @click="goDetail(item.complaintId)"><view class="card-head"><text class="type">{{ item.typeText }}</text><text class="status">{{ item.statusText }}</text></view><text class="service">{{ item.serviceItemName }} · {{ item.receiverName }}</text><text class="content">{{ item.content }}</text><view class="card-foot"><text>{{ formatTime(item.updateTime) }}</text><text>{{ item.complaintNo }} ›</text></view></view><empty-state v-if="!store.merchantComplaints.length" title="暂无投诉事项" description="顾客提交的服务投诉会显示在这里" /></view></view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import EmptyState from '@/components/base/empty-state.vue'
import { COMPLAINT_STATUS } from '@/constants/complaint-status.js'
import { ROLES } from '@/constants/roles.js'
import { useComplaintStore } from '@/store/complaint.js'
import { requireRole } from '@/utils/permission.js'
const store = useComplaintStore(); const status = ref(''); const filters = [{ label: '全部', value: '' }, { label: '待响应', value: String(COMPLAINT_STATUS.SUBMITTED) }, { label: '平台仲裁', value: String(COMPLAINT_STATUS.ADMIN_REVIEW) }, { label: '已裁决', value: String(COMPLAINT_STATUS.RESOLVED) }]; const pendingCount = computed(() => store.merchantComplaints.filter((item) => [COMPLAINT_STATUS.SUBMITTED, COMPLAINT_STATUS.MERCHANT_PROCESSING].includes(item.status)).length); onShow(() => { if (requireRole(ROLES.MERCHANT_MEMBER)) load() }); function load() { return store.fetchMerchantComplaints(status.value === '' ? {} : { status: Number(status.value) }) } function changeFilter(value) { status.value = value; load() } function formatTime(value) { return value?.replace('T',' ').replace('+08:00','').slice(0,16) || '--' } function goDetail(id) { uni.navigateTo({ url: `/subpkg-merchant/complaint-detail/index?id=${id}` }) }
</script>
<style lang="scss" scoped>
.page-shell{min-height:100vh;padding:24rpx $spacing-base 60rpx;background:$page-gradient}.hero{display:flex;align-items:center;justify-content:space-between;padding:28rpx;border-radius:31rpx;color:#fff;background:linear-gradient(135deg,#d56b34,#f29a55);box-shadow:$shadow-float}.eyebrow,.title,.subtitle,.service,.content{display:block}.eyebrow{font-size:$font-size-xs;opacity:.78}.title{margin-top:8rpx;font-size:34rpx;font-weight:700}.subtitle{margin-top:8rpx;font-size:$font-size-xs;opacity:.84}.filter-scroll{margin:19rpx 0}.filters{display:flex;gap:10rpx;white-space:nowrap}.filters text{padding:12rpx 20rpx;border-radius:$radius-round;color:$text-color-hint;background:#fff;font-size:$font-size-xs}.filters text.active{color:#fff;background:$warning-color}.complaint-card{margin-top:16rpx;padding:24rpx;border:$glass-border-soft;border-radius:27rpx;background:$surface-gradient;box-shadow:$shadow-sm}.card-head,.card-foot{display:flex;align-items:center;justify-content:space-between}.type{color:$text-color;font-weight:700}.status{padding:6rpx 13rpx;border-radius:$radius-round;color:$warning-color;background:#fff2eb;font-size:$font-size-xs}.service{margin-top:14rpx;color:$primary-color;font-size:$font-size-xs}.content{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;margin-top:10rpx;color:$text-color-secondary;font-size:$font-size-sm;line-height:1.6}.card-foot{margin-top:18rpx;padding-top:15rpx;border-top:1rpx solid $divider-color;color:$text-color-disabled;font-size:$font-size-xs}.loading{display:flex;justify-content:center;padding:120rpx 0}
</style>
