<template>
  <view v-if="detail" class="page-shell"><view class="status-card"><view><text class="eyebrow">{{ detail.typeText }} · {{ detail.complaintNo }}</text><text class="title">{{ detail.statusText }}</text><text class="subtitle">{{ detail.content }}</text></view><u-icon name="chat-fill" size="36" color="#FFFFFF" /></view><view class="detail-card"><text class="section-title">关联订单</text><view class="row"><text>服务项目</text><text>{{ detail.order?.serviceItemName }}</text></view><view class="row"><text>订单编号</text><text>{{ detail.order?.orderNo }}</text></view><view class="row"><text>顾客</text><text>{{ detail.order?.receiverName }}</text></view><view class="row"><text>订单金额</text><text>¥{{ detail.order?.totalAmount }}</text></view></view><view class="detail-card"><text class="section-title">双方材料</text><text class="material-label">顾客说明</text><text class="material-copy">{{ detail.content }}</text><view v-for="item in detail.customerEvidence" :key="item.name" class="evidence"><text>{{ item.name }}</text><text>{{ item.value }}</text></view><template v-if="detail.merchantStatement"><text class="material-label merchant">商户说明</text><text class="material-copy">{{ detail.merchantStatement }}</text><view v-for="item in detail.merchantEvidence" :key="item.name" class="evidence"><text>{{ item.name }}</text><text>{{ item.value }}</text></view></template></view><view class="detail-card"><text class="section-title">处理记录</text><view v-for="record in detail.tracks" :key="record.trackId" class="record"><view class="dot" /><view><text class="record-title">{{ record.operator }}</text><text class="record-copy">{{ record.content }}</text><text class="record-time">{{ formatTime(record.createTime) }}</text></view></view></view><view v-if="canProcess" class="response-card"><text class="section-title">商户响应</text><textarea v-model="statement" maxlength="500" class="statement" placeholder="说明核查结果、沟通情况和处理建议" /><view class="evidence-input"><input v-model="evidenceName" placeholder="凭证名称，如：服务记录" /><input v-model="evidenceValue" placeholder="凭证说明或文件地址" /></view><view class="bottom-actions"><button class="secondary" @click="process('escalate')">提交平台仲裁</button><button class="primary" @click="process('resolve')">协商解决</button></view></view><view v-if="detail.decision" class="decision-card"><text>{{ detail.decision.label }}</text><text v-if="detail.decision.refundAmount">退款 ¥{{ detail.decision.refundAmount }}</text><text>{{ detail.decision.remark }}</text></view></view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { COMPLAINT_STATUS } from '@/constants/complaint-status.js'
import { ROLES } from '@/constants/roles.js'
import { useComplaintStore } from '@/store/complaint.js'
import { requireRole } from '@/utils/permission.js'
const store = useComplaintStore(); const id = ref(null); const statement = ref(''); const evidenceName = ref('服务履约说明'); const evidenceValue = ref(''); const detail = computed(() => store.currentMerchantComplaint); const canProcess = computed(() => [COMPLAINT_STATUS.SUBMITTED, COMPLAINT_STATUS.MERCHANT_PROCESSING].includes(detail.value?.status)); onLoad(async (options) => { if (!requireRole(ROLES.MERCHANT_MEMBER)) return; id.value = String(options.id || ''); const value = await store.fetchMerchantComplaintDetail(id.value); statement.value = value.merchantStatement || '' }); function formatTime(value) { return value?.replace('T',' ').replace('+08:00','').slice(0,16) || '--' } async function process(action) { if (statement.value.trim().length < 10) return uni.showToast({ title: '请至少填写10个字的处理说明', icon: 'none' }); const evidence = evidenceValue.value.trim() ? [{ name: evidenceName.value.trim() || '商户凭证', value: evidenceValue.value.trim() }] : []; await store.processMerchantComplaint(id.value, action, { statement: statement.value.trim(), evidence }); uni.showToast({ title: action === 'resolve' ? '投诉已协商解决' : '已提交平台仲裁', icon: 'success' }) }
</script>
<style lang="scss" scoped>
.page-shell{min-height:100vh;padding:24rpx $spacing-base 60rpx;background:$page-gradient}.status-card{display:flex;align-items:center;justify-content:space-between;padding:28rpx;border-radius:31rpx;color:#fff;background:linear-gradient(135deg,#d56b34,#f29a55);box-shadow:$shadow-float}.eyebrow,.title,.subtitle,.material-label,.material-copy,.record-title,.record-copy,.record-time,.decision-card text{display:block}.eyebrow{font-size:$font-size-xs;opacity:.78}.title{margin-top:8rpx;font-size:34rpx;font-weight:700}.subtitle{max-width:560rpx;margin-top:8rpx;font-size:$font-size-xs;line-height:1.55;opacity:.84}.detail-card,.response-card,.decision-card{margin-top:18rpx;padding:24rpx;border:$glass-border-soft;border-radius:27rpx;background:$surface-gradient;box-shadow:$shadow-sm}.section-title{color:$text-color;font-size:$font-size-md;font-weight:700}.row,.evidence{display:flex;justify-content:space-between;gap:20rpx;padding:16rpx 0;border-bottom:1rpx solid $divider-color;color:$text-color-hint;font-size:$font-size-sm}.row text:last-child,.evidence text:last-child{color:$text-color;text-align:right}.material-label{margin-top:20rpx;color:$warning-color;font-size:$font-size-xs;font-weight:700}.material-label.merchant{color:$primary-color}.material-copy{margin-top:8rpx;color:$text-color-secondary;font-size:$font-size-sm;line-height:1.65}.record{display:flex;gap:14rpx;padding-top:19rpx}.dot{width:15rpx;height:15rpx;margin-top:7rpx;border:4rpx solid #ffe2ca;border-radius:50%;background:$warning-color}.record-title{color:$text-color;font-size:$font-size-sm;font-weight:600}.record-copy{margin-top:5rpx;color:$text-color-secondary;font-size:$font-size-xs;line-height:1.55}.record-time{margin-top:5rpx;color:$text-color-disabled;font-size:21rpx}.statement{width:100%;height:180rpx;margin-top:18rpx;padding:17rpx;border:1rpx solid $border-color;border-radius:20rpx;background:#fff;font-size:$font-size-sm}.evidence-input{display:grid;gap:12rpx;margin-top:14rpx}.evidence-input input{height:72rpx;padding:0 17rpx;border:1rpx solid $border-color;border-radius:18rpx;background:#fff;font-size:$font-size-sm}.bottom-actions{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;margin-top:18rpx}.bottom-actions button{height:76rpx;margin:0;border:0;border-radius:$radius-round;line-height:76rpx}.secondary{color:$warning-color;background:#fff2eb}.primary{color:#fff;background:linear-gradient(135deg,#e7833b,#f4a259)}.bottom-actions button::after{border:0}.decision-card{color:$success-color;background:#e9fbf7;font-size:$font-size-sm;line-height:1.7}
</style>
