<template>
  <view class="page-shell"><view class="notice"><u-icon name="lock-fill" size="20" color="#3A7BF7" /><text>商户成员用于内部运营，不等同于护理人员。岗位决定其可访问的商户功能和数据范围。</text></view><view class="form-card"><text class="section-title">成员账号</text><text class="field-label">手机号 *</text><input v-model="form.phone" type="number" maxlength="11" class="text-input" placeholder="请输入成员手机号" /><text class="field-label">姓名</text><input v-model="form.name" maxlength="20" class="text-input" placeholder="选填" /><text class="field-label">内部岗位 *</text><view class="position-list"><view v-for="position in positions" :key="position.value" :class="{ active: form.position === position.value }" @click="form.position = position.value"><view><text class="position-name">{{ position.label }}</text><text class="position-desc">{{ position.description }}</text></view><u-icon :name="form.position === position.value ? 'checkmark-circle-fill' : 'circle'" size="21" :color="form.position === position.value ? '#3A7BF7' : '#C5CDD8'" /></view></view></view><button class="submit-button" :disabled="submitting" @click="submit">{{ submitting ? '发送中...' : '邀请加入商户' }}</button></view>
</template>
<script setup>
import { reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { ROLES } from '@/constants/roles.js'
import { MERCHANT_POSITION_OPTIONS } from '@/constants/team-status.js'
import { useMerchantTeamStore } from '@/store/merchant-team.js'
import { requireRole } from '@/utils/permission.js'
const teamStore = useMerchantTeamStore(); const positions = MERCHANT_POSITION_OPTIONS.filter((item) => item.value !== 'OWNER'); const submitting = ref(false); const form = reactive({ phone: '', name: '', position: 'OPERATOR' }); onLoad(() => requireRole(ROLES.MERCHANT_MEMBER)); async function submit() { if (!/^1\d{10}$/.test(form.phone)) return uni.showToast({ title: '请输入正确的手机号', icon: 'none' }); submitting.value = true; try { await teamStore.inviteMember({ ...form }); uni.showToast({ title: '成员邀请已发送', icon: 'success' }); setTimeout(() => uni.navigateBack(), 600) } finally { submitting.value = false } }
</script>
<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 24rpx $spacing-base 70rpx; background: $page-gradient; }.notice { display: flex; gap: 12rpx; padding: 20rpx; border-radius: 22rpx; color: $text-color-secondary; background: $primary-bg; font-size: $font-size-xs; line-height: 1.6; }.form-card { margin-top: 18rpx; padding: 25rpx; border: $glass-border-soft; border-radius: 28rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.section-title { color: $text-color; font-size: $font-size-md; font-weight: 700; }.field-label { display: block; margin-top: 22rpx; color: $text-color-secondary; font-size: $font-size-sm; font-weight: 600; }.text-input { width: 100%; height: 76rpx; margin-top: 9rpx; padding: 0 17rpx; border: 1rpx solid $border-color; border-radius: 20rpx; color: $text-color; background: rgba(255,255,255,.78); font-size: $font-size-sm; }.position-list { display: grid; gap: 11rpx; margin-top: 12rpx; }.position-list>view { display: flex; align-items: center; justify-content: space-between; gap: 15rpx; padding: 18rpx; border: 2rpx solid transparent; border-radius: 20rpx; background: $bg-color-grey; }.position-list>view.active { border-color: rgba(58,123,247,.28); background: $primary-bg; }.position-name,.position-desc { display: block; }.position-name { color: $text-color; font-size: $font-size-sm; font-weight: 700; }.position-desc { margin-top: 5rpx; color: $text-color-hint; font-size: $font-size-xs; }.submit-button { width: 100%; height: 82rpx; margin-top: 24rpx; border: 0; border-radius: $radius-round; color: #fff; background: $primary-gradient; line-height: 82rpx; }.submit-button::after { border: 0; }
</style>
