<template>
  <view class="page-shell"><view class="notice"><u-icon name="info-circle" size="21" color="#00A89D" /><text>邀请将发送给已认证护理人员，对方确认后才会进入合作中状态并出现在派单候选列表。</text></view><view class="form-card"><text class="section-title">护理人员信息</text><text class="field-label">手机号 *</text><input v-model="form.phone" type="number" maxlength="11" class="text-input" placeholder="请输入已认证护理人员手机号" /><text class="field-label">姓名</text><input v-model="form.name" maxlength="20" class="text-input" placeholder="选填，用于邀请记录展示" /><text class="field-label">从业年限</text><input v-model="form.workYears" type="number" class="text-input" placeholder="选填" /><text class="field-label">服务区域</text><input v-model="serviceAreasText" maxlength="100" class="text-input" placeholder="多个区域使用顿号分隔" /><text class="field-label">擅长技能</text><view class="skill-grid"><view v-for="skill in skillOptions" :key="skill" :class="{ active: form.skills.includes(skill) }" @click="toggleSkill(skill)">{{ skill }}</view></view><text class="field-label">邀请备注</text><textarea v-model="form.remark" maxlength="200" class="textarea-input" placeholder="可填写合作范围、排班要求等说明" /></view><button class="submit-button" :disabled="submitting" @click="submit">{{ submitting ? '发送中...' : '发送合作邀请' }}</button></view>
</template>
<script setup>
import { computed, reactive, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { CAREGIVER_SKILL_OPTIONS } from '@/constants/caregiver-status.js'
import { ROLES } from '@/constants/roles.js'
import { useMerchantTeamStore } from '@/store/merchant-team.js'
import { requireRole } from '@/utils/permission.js'
const teamStore = useMerchantTeamStore(); const skillOptions = CAREGIVER_SKILL_OPTIONS; const submitting = ref(false); const form = reactive({ phone: '', name: '', workYears: '', serviceAreas: [], skills: [], remark: '' }); const serviceAreasText = computed({ get: () => form.serviceAreas.join('、'), set: (value) => { form.serviceAreas = value.split(/[、,，]/).map((item) => item.trim()).filter(Boolean) } }); onLoad(() => requireRole(ROLES.MERCHANT_MEMBER)); function toggleSkill(skill) { const index = form.skills.indexOf(skill); if (index >= 0) form.skills.splice(index, 1); else form.skills.push(skill) } async function submit() { if (!/^1\d{10}$/.test(form.phone)) return uni.showToast({ title: '请输入正确的手机号', icon: 'none' }); submitting.value = true; try { await teamStore.inviteCaregiver({ ...form, workYears: Number(form.workYears || 0) }); uni.showToast({ title: '邀请已发送', icon: 'success' }); setTimeout(() => uni.navigateBack(), 600) } finally { submitting.value = false } }
</script>
<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 24rpx $spacing-base 70rpx; background: $page-gradient; }.notice { display: flex; gap: 12rpx; padding: 20rpx; border-radius: 22rpx; color: $text-color-secondary; background: #e9fbf7; font-size: $font-size-xs; line-height: 1.6; }.form-card { margin-top: 18rpx; padding: 25rpx; border: $glass-border-soft; border-radius: 28rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.section-title { color: $text-color; font-size: $font-size-md; font-weight: 700; }.field-label { display: block; margin-top: 22rpx; color: $text-color-secondary; font-size: $font-size-sm; font-weight: 600; }.text-input,.textarea-input { width: 100%; margin-top: 9rpx; border: 1rpx solid $border-color; border-radius: 20rpx; color: $text-color; background: rgba(255,255,255,.78); font-size: $font-size-sm; }.text-input { height: 76rpx; padding: 0 17rpx; }.textarea-input { height: 160rpx; padding: 17rpx; }.skill-grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 10rpx; margin-top: 11rpx; }.skill-grid view { padding: 14rpx 6rpx; border: 1rpx solid $border-color; border-radius: 18rpx; color: $text-color-hint; background: #fff; font-size: $font-size-xs; text-align: center; }.skill-grid view.active { border-color: rgba(0,168,157,.3); color: #008d84; background: #e9fbf7; }.submit-button { width: 100%; height: 82rpx; margin-top: 24rpx; border: 0; border-radius: $radius-round; color: #fff; background: linear-gradient(135deg,#008d84,#00b8a9); line-height: 82rpx; }.submit-button::after { border: 0; }
</style>
