<template>
  <view class="page-shell">
    <view class="hero-card"><view><text class="eyebrow">商户团队</text><text class="title">人员与合作关系</text><text class="subtitle">维护护理团队、可接单状态和商户内部岗位</text></view><view class="hero-icon"><u-icon name="account-fill" size="36" color="#FFFFFF" /></view></view>
    <view class="tabs"><view class="tab" :class="{ active: currentTab === 'caregiver' }" @click="currentTab = 'caregiver'">护理团队</view><view class="tab" :class="{ active: currentTab === 'member' }" @click="currentTab = 'member'">商户成员</view></view>

    <template v-if="currentTab === 'caregiver'">
      <view class="summary-grid"><view><text>{{ summary?.total || 0 }}</text><text>团队人数</text></view><view><text>{{ summary?.available || 0 }}</text><text>可接单</text></view><view><text>{{ summary?.invited || 0 }}</text><text>待确认</text></view><view><text>{{ summary?.suspended || 0 }}</text><text>已停用</text></view></view>
      <view class="tool-row"><view class="search-box"><u-icon name="search" size="18" color="#8E9DAE" /><input v-model="keyword" placeholder="搜索姓名、手机号或技能" @confirm="loadCaregivers" /></view><button class="add-button" @click="goInviteCaregiver">+ 邀请护理人员</button></view>
      <scroll-view scroll-x class="filter-scroll"><view class="filter-row"><text v-for="filter in caregiverFilters" :key="filter.value" :class="{ active: caregiverStatus === filter.value }" @click="changeStatus(filter.value)">{{ filter.label }}</text></view></scroll-view>
      <view v-if="teamStore.loading" class="loading-wrap"><u-loading-icon size="28" color="#00A89D" /></view>
      <view v-else class="person-list"><view v-for="person in teamStore.caregivers" :key="person.relationId" class="person-card" @click="goCaregiverDetail(person.relationId)"><view class="avatar caregiver"><u-icon name="server-man" size="26" color="#00A89D" /></view><view class="person-copy"><view class="name-row"><text class="person-name">{{ person.name }}</text><text class="status-badge" :class="getCooperationStatusMeta(person.status).tone">{{ getCooperationStatusMeta(person.status).label }}</text><text v-if="person.available" class="available-badge">可接单</text></view><text class="person-meta">{{ person.phone }} · {{ person.workYears }}年经验 · ★ {{ person.rating || '--' }}</text><view class="tag-row"><text v-for="skill in person.skills.slice(0, 3)" :key="skill">{{ skill }}</text></view><text class="person-note">{{ person.scheduleSummary }} · 当前 {{ person.currentTaskCount }} 个任务</text></view><u-icon name="arrow-right" size="16" color="#C5CDD8" /></view><empty-state v-if="!teamStore.caregivers.length" text="暂无符合条件的护理人员" /></view>
    </template>

    <template v-else>
      <view class="member-head"><view><text class="section-title">内部岗位</text><text class="section-desc">负责人与运营、调度、财务岗位分开授权</text></view><button class="add-button" @click="goInviteMember">+ 邀请成员</button></view>
      <view class="person-list"><view v-for="member in teamStore.members" :key="member.memberId" class="person-card"><view class="avatar member"><u-icon name="account" size="26" color="#3A7BF7" /></view><view class="person-copy"><view class="name-row"><text class="person-name">{{ member.name }}</text><text class="position-badge">{{ getPositionLabel(member.position) }}</text><text class="status-badge" :class="member.status === 'ACTIVE' ? 'success' : 'danger'">{{ member.status === 'ACTIVE' ? '启用' : '停用' }}</text></view><text class="person-meta">{{ member.phone }} · 加入于 {{ member.joinTime }}</text><text class="person-note">{{ member.permissions.includes('*') ? '拥有全部商户权限' : `已配置 ${member.permissions.length} 项权限` }}</text></view><text v-if="member.position !== 'OWNER'" class="action-link" @click.stop="toggleMember(member)">{{ member.status === 'ACTIVE' ? '停用' : '启用' }}</text></view></view>
    </template>
  </view>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import EmptyState from '@/components/base/empty-state.vue'
import { ROLES } from '@/constants/roles.js'
import { getCooperationStatusMeta, getPositionLabel } from '@/constants/team-status.js'
import { useMerchantTeamStore } from '@/store/merchant-team.js'
import { requireRole } from '@/utils/permission.js'

const teamStore = useMerchantTeamStore()
const currentTab = ref('caregiver')
const caregiverStatus = ref('')
const keyword = ref('')
const summary = computed(() => teamStore.summary)
const caregiverFilters = [{ label: '全部', value: '' }, { label: '合作中', value: 'ACTIVE' }, { label: '待确认', value: 'INVITED' }, { label: '已停用', value: 'SUSPENDED' }]
onShow(async () => { if (!requireRole(ROLES.MERCHANT_MEMBER)) return; await Promise.all([loadCaregivers(), teamStore.fetchMembers()]) })
watch(currentTab, async (value) => { if (value === 'member') await teamStore.fetchMembers() })
async function loadCaregivers() { await teamStore.fetchCaregivers({ ...(caregiverStatus.value ? { status: caregiverStatus.value } : {}), ...(keyword.value.trim() ? { keyword: keyword.value.trim() } : {}) }) }
function changeStatus(status) { caregiverStatus.value = status; loadCaregivers() }
function goCaregiverDetail(id) { uni.navigateTo({ url: `/subpkg-merchant/caregiver-detail/index?id=${id}` }) }
function goInviteCaregiver() { uni.navigateTo({ url: '/subpkg-merchant/caregiver-invite/index' }) }
function goInviteMember() { uni.navigateTo({ url: '/subpkg-merchant/member-invite/index' }) }
function toggleMember(member) { const action = member.status === 'ACTIVE' ? 'disable' : 'enable'; uni.showModal({ title: `${action === 'disable' ? '停用' : '启用'}成员`, content: `确认${action === 'disable' ? '停用' : '启用'}${member.name}吗？`, success: async ({ confirm }) => { if (!confirm) return; await teamStore.updateMemberStatus(member.memberId, action); uni.showToast({ title: '成员状态已更新', icon: 'success' }) } }) }
</script>

<style lang="scss" scoped>
.page-shell { min-height: 100vh; padding: 25rpx $spacing-base 70rpx; background: $page-gradient; }.hero-card { display: flex; align-items: center; justify-content: space-between; min-height: 205rpx; padding: 30rpx; border-radius: 32rpx; color: #fff; background: linear-gradient(135deg,#116b68,#00a89d 55%,#38c6b5); box-shadow: $shadow-float; }.eyebrow,.title,.subtitle { display: block; }.eyebrow { font-size: $font-size-xs; opacity: .76; }.title { margin-top: 8rpx; font-size: 37rpx; font-weight: 700; }.subtitle { margin-top: 9rpx; font-size: $font-size-xs; opacity: .82; }.hero-icon { display: flex; align-items: center; justify-content: center; width: 82rpx; height: 82rpx; border-radius: 27rpx; background: rgba(255,255,255,.18); }.tabs { display: grid; grid-template-columns: repeat(2,1fr); margin-top: 20rpx; padding: 7rpx; border-radius: $radius-round; background: rgba(230,236,244,.78); }.tab { padding: 15rpx; border-radius: $radius-round; color: $text-color-hint; font-size: $font-size-sm; text-align: center; }.tab.active { color: #008d84; background: #fff; box-shadow: $shadow-sm; font-weight: 700; }
.summary-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 12rpx; margin-top: 20rpx; }.summary-grid>view { padding: 20rpx 8rpx; border: $glass-border-soft; border-radius: 22rpx; background: $surface-gradient; text-align: center; }.summary-grid text { display: block; }.summary-grid text:first-child { color: $text-color; font-size: 34rpx; font-weight: 700; }.summary-grid text:last-child { margin-top: 5rpx; color: $text-color-hint; font-size: 21rpx; }.tool-row,.member-head { display: flex; align-items: center; gap: 12rpx; margin-top: 22rpx; }.search-box { display: flex; align-items: center; gap: 10rpx; min-width: 0; height: 70rpx; flex: 1; padding: 0 17rpx; border: 1rpx solid $border-color; border-radius: 21rpx; background: rgba(255,255,255,.76); }.search-box input { min-width: 0; flex: 1; font-size: $font-size-xs; }.add-button { height: 70rpx; margin: 0; padding: 0 19rpx; border: 0; border-radius: 21rpx; color: #fff; background: linear-gradient(135deg,#008d84,#00b8a9); font-size: $font-size-xs; line-height: 70rpx; }.add-button::after { border: 0; }.filter-scroll { margin-top: 16rpx; white-space: nowrap; }.filter-row { display: flex; gap: 10rpx; }.filter-row text { padding: 10rpx 18rpx; border-radius: $radius-round; color: $text-color-hint; background: rgba(255,255,255,.75); font-size: $font-size-xs; }.filter-row text.active { color: #008d84; background: #e9fbf7; font-weight: 600; }
.loading-wrap { display: flex; justify-content: center; padding: 120rpx 0; }.person-list { margin-top: 17rpx; }.person-card { display: flex; align-items: center; gap: 15rpx; margin-bottom: 14rpx; padding: 21rpx; border: $glass-border-soft; border-radius: 26rpx; background: $surface-gradient; box-shadow: $shadow-sm; }.avatar { display: flex; align-items: center; justify-content: center; width: 72rpx; height: 72rpx; flex-shrink: 0; border-radius: 23rpx; }.avatar.caregiver { background: #e9fbf7; }.avatar.member { background: $primary-bg; }.person-copy { min-width: 0; flex: 1; }.name-row { display: flex; align-items: center; gap: 8rpx; }.person-name { color: $text-color; font-size: $font-size-base; font-weight: 700; }.status-badge,.position-badge,.available-badge { padding: 4rpx 9rpx; border-radius: $radius-round; font-size: 19rpx; }.status-badge.success,.available-badge { color: #008d84; background: #e9fbf7; }.status-badge.warning { color: #d87831; background: #fff4ea; }.status-badge.danger { color: $error-color; background: #fff0f1; }.status-badge.muted { color: $text-color-hint; background: $bg-color-grey; }.position-badge { color: $primary-color; background: $primary-bg; }.person-meta,.person-note { display: block; }.person-meta { margin-top: 6rpx; color: $text-color-hint; font-size: $font-size-xs; }.tag-row { display: flex; gap: 7rpx; margin-top: 9rpx; overflow: hidden; }.tag-row text { flex-shrink: 0; padding: 5rpx 9rpx; border-radius: $radius-round; color: #008d84; background: #e9fbf7; font-size: 18rpx; }.person-note { margin-top: 8rpx; color: $text-color-secondary; font-size: 21rpx; }.section-title,.section-desc { display: block; }.section-title { color: $text-color; font-size: $font-size-md; font-weight: 700; }.section-desc { margin-top: 5rpx; color: $text-color-hint; font-size: $font-size-xs; }.member-head>view { flex: 1; }.action-link { color: $primary-color; font-size: $font-size-xs; }
</style>
