<template>
  <view v-if="detail" class="page-shell"><view class="status-card"><view><text class="eyebrow">{{ typeMeta.label }}</text><text class="title">{{ detail.title }}</text><text class="subtitle">{{ detail.description }}</text></view><u-icon name="warning-fill" size="36" color="#FFFFFF" /></view><view class="detail-card"><text class="section-title">关联订单</text><view class="row"><text>服务项目</text><text>{{ detail.order?.serviceItemName }}</text></view><view class="row"><text>订单编号</text><text>{{ detail.order?.orderNo }}</text></view><view class="row"><text>预约时间</text><text>{{ detail.order?.serviceDate }}</text></view><view class="row"><text>顾客</text><text>{{ detail.order?.receiverName }}</text></view></view><view v-if="detail.evidence?.length" class="detail-card"><text class="section-title">异常凭证</text><view v-for="item in detail.evidence" :key="item.name" class="evidence"><text>{{ item.name }}</text><text>{{ item.value }}</text></view></view><view class="detail-card"><text class="section-title">处理记录</text><view v-for="record in detail.records" :key="`${record.action}-${record.time}`" class="record"><view class="dot" /><view><text class="record-title">{{ record.title }}</text><text v-if="record.remark" class="record-remark">{{ record.remark }}</text><text class="record-time">{{ formatTime(record.time) }} · {{ record.operator }}</text></view></view></view><view v-if="canProcess" class="bottom-actions"><template v-if="detail.type === 'ABNORMAL_CHECK_IN'"><button class="secondary" @click="process('reject-check-in')">驳回并提交平台</button><button class="primary" @click="process('approve-check-in')">确认签到有效</button></template><template v-else><button class="secondary" @click="process('request-refund')">建议退款</button><button class="primary" @click="process('retry-dispatch')">重新派单</button></template></view></view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { EXCEPTION_STATUS, getExceptionTypeMeta } from '@/constants/aftersales-status.js'
import { ROLES } from '@/constants/roles.js'
import { useAftersalesStore } from '@/store/aftersales.js'
import { requireRole } from '@/utils/permission.js'
const store = useAftersalesStore(); const id = ref(null); const detail = computed(() => store.currentException); const typeMeta = computed(() => getExceptionTypeMeta(detail.value?.type)); const canProcess = computed(() => [EXCEPTION_STATUS.OPEN, EXCEPTION_STATUS.MERCHANT_PROCESSING].includes(detail.value?.status)); onLoad(async (options) => { if (!requireRole(ROLES.MERCHANT_MEMBER)) return; id.value = Number(options.id); await store.fetchMerchantExceptionDetail(id.value) }); function formatTime(value) { return value?.replace('T', ' ').replace('+08:00', '').slice(0,16) || '--' } function process(action) { const labels = { 'approve-check-in': '确认签到有效', 'reject-check-in': '驳回异常签到', 'retry-dispatch': '重新派单', 'request-refund': '建议退款' }; uni.showModal({ title: labels[action], editable: true, placeholderText: '填写处理说明（选填）', success: async ({ confirm, content }) => { if (!confirm) return; await store.processMerchantException(id.value, action, { remark: content || '' }); uni.showToast({ title: '处理成功', icon: 'success' }); if (action === 'retry-dispatch') setTimeout(() => uni.navigateTo({ url: `/subpkg-merchant/dispatch/index?id=${detail.value.orderId}&mode=redispatch` }), 500) } }) }
</script>
<style lang="scss" scoped>
.page-shell { min-height:100vh;padding:24rpx $spacing-base 150rpx;background:$page-gradient; }.status-card { display:flex;align-items:center;justify-content:space-between;min-height:190rpx;padding:29rpx;border-radius:31rpx;color:#fff;background:linear-gradient(135deg,#d56b34,#f29a55);box-shadow:$shadow-float; }.eyebrow,.title,.subtitle { display:block; }.eyebrow { font-size:$font-size-xs;opacity:.76; }.title { margin-top:7rpx;font-size:32rpx;font-weight:700; }.subtitle { max-width:550rpx;margin-top:8rpx;font-size:$font-size-xs;line-height:1.55;opacity:.84; }.detail-card { margin-top:18rpx;padding:24rpx;border:$glass-border-soft;border-radius:27rpx;background:$surface-gradient;box-shadow:$shadow-sm; }.section-title { color:$text-color;font-size:$font-size-md;font-weight:700; }.row,.evidence { display:flex;justify-content:space-between;gap:20rpx;padding:17rpx 0;border-bottom:1rpx solid $divider-color;color:$text-color-hint;font-size:$font-size-sm; }.row text:last-child,.evidence text:last-child { color:$text-color;text-align:right; }.record { display:flex;gap:14rpx;padding-top:19rpx; }.dot { width:15rpx;height:15rpx;margin-top:7rpx;border:4rpx solid #ffe2ca;border-radius:50%;background:$warning-color; }.record-title,.record-remark,.record-time { display:block; }.record-title { color:$text-color;font-size:$font-size-sm;font-weight:600; }.record-remark { margin-top:5rpx;color:$text-color-secondary;font-size:$font-size-xs; }.record-time { margin-top:5rpx;color:$text-color-disabled;font-size:21rpx; }.bottom-actions { position:fixed;right:0;bottom:0;left:0;display:grid;grid-template-columns:1fr 1fr;gap:12rpx;padding:18rpx $spacing-base calc(18rpx + env(safe-area-inset-bottom));background:rgba(249,251,255,.95); }.bottom-actions button { height:78rpx;margin:0;border:0;border-radius:$radius-round;line-height:78rpx; }.secondary { color:$warning-color;background:#fff4ea; }.primary { color:#fff;background:linear-gradient(135deg,#e7833b,#f4a259); }.bottom-actions button::after { border:0; }
</style>
